import HDXLean.AlgebraicGeometryCauchyBinet

/-!
# Concrete Section 4 assembly

This downstream module replaces the old generic polynomial-evaluation
certificate at each tower level by exactly two pieces of meaningful data:

* the structural factorization `M(x) = U * diagonal x * Zᵀ`;
* the cited Eisenbud conclusion that the resulting explicit maximal-minor
  coefficient vectors are linearly independent.

The Cauchy--Binet and Boolean-cube evaluation steps are then constructed
internally.  A conversion to the existing `SectionFourInput` keeps the rest of
the project unchanged while placing the trust boundary at the cited theorem.
-/

namespace HDXLean

universe u

section Levels

variable {F : Type u} [Field F] [Fintype F]
variable (P : SquareFieldParameters F)

/-- Concrete maximal-minor data at one Riemann--Roch level.  There is no
generic function-evaluation certificate or polynomial-model identification
field. -/
structure ConcreteMaximalMinorLevelData {g : ℕ}
    (level : RiemannRochLevelInput P g) where
  matrix : MultiplicationMatrixData level.directions
  MinorIndex : Type
  [minorFintype : Fintype MinorIndex]
  index_card : Fintype.card MinorIndex = Nat.choose (3 * (g / 4)) (g / 4)
  selection : MaximalMinorSelection level.directions matrix MinorIndex
  factorization : CoordinateRankOneFactorization level.directions matrix
  eisenbud : factorization.EisenbudCoefficientIndependenceInput selection

attribute [instance] ConcreteMaximalMinorLevelData.minorFintype

namespace ConcreteMaximalMinorLevelData

/-- Package the concrete data into the legacy interface.  The apparent
polynomial model is now literally the squarefree coefficient space, and its
evaluation certificate is generated by the proved Cauchy--Binet identity. -/
noncomputable def toMaximalMinorLevelData {g : ℕ}
    {level : RiemannRochLevelInput P g}
    (data : ConcreteMaximalMinorLevelData P level) :
    MaximalMinorLevelData P level := by
  let eisenbud : EisenbudMaximalMinorInput (F := F) data.MinorIndex :=
    { PolynomialModel := BooleanCube.Coefficients (F := F) level.t
      polynomialMinor :=
        data.factorization.selectedMaximalMinorCoefficients data.selection
      oneGeneric := data.eisenbud.oneGeneric
      oneGeneric_proof := data.eisenbud.oneGeneric_proof
      maximalMinors_independent := fun honeGeneric ↦
        data.eisenbud.maximalMinorCoefficients_independent
          honeGeneric }
  let evaluation : BooleanCubeEvaluationCertificate eisenbud
      (selectedMaximalMinor level.directions data.matrix data.selection) :=
    BooleanCubeEvaluationCertificate.ofSquarefreeModel eisenbud
      (selectedMaximalMinor level.directions data.matrix data.selection)
      (LinearEquiv.refl F
        (BooleanCube.Coefficients (F := F) level.t))
      (fun j ↦ by
        change BooleanCube.evaluationLinear (F := F) level.t
            (data.factorization.selectedMaximalMinorCoefficients
              data.selection j) =
          selectedMaximalMinor level.directions data.matrix data.selection j
        exact
          data.factorization.evaluationLinear_selectedMaximalMinorCoefficients
            data.selection j)
  exact
    { matrix := data.matrix
      MinorIndex := data.MinorIndex
      index_card := data.index_card
      selection := data.selection
      eisenbud := eisenbud
      evaluation := evaluation }

/-- Proposition 4.7 for concrete level data, with independence transported
internally through Boolean-cube evaluation. -/
theorem selectedMaximalMinor_linearIndependent {g : ℕ}
    {level : RiemannRochLevelInput P g}
    (data : ConcreteMaximalMinorLevelData P level) :
    LinearIndependent F
      (selectedMaximalMinor level.directions data.matrix data.selection) :=
  data.factorization.selectedMaximalMinor_linearIndependent
    data.selection data.eisenbud

/-- The revised rectangular-minor dimension lower bound furnished by the concrete
minor family. -/
theorem minorCount_le_finrank {g : ℕ}
    {level : RiemannRochLevelInput P g}
    (data : ConcreteMaximalMinorLevelData P level) :
    Nat.choose (3 * (g / 4)) (g / 4) ≤
      Module.finrank F (affineFunctions F level.directions) :=
  data.toMaximalMinorLevelData.minorCount_le_finrank

end ConcreteMaximalMinorLevelData

/-- Section 4 input with the project-owned determinant and evaluation algebra
removed from its trust boundary. -/
structure ConcreteSectionFourInput
    (tower : GarciaStichtenothTowerInput P) where
  constructionThreshold : ℕ
  level : ∀ r, constructionThreshold ≤ r →
    1 + (P.q - 2) * tower.genus r ≤ tower.rationalPointCount r →
      RiemannRochLevelInput P (tower.genus r)
  minors : ∀ r (hr : constructionThreshold ≤ r)
      (hpoints :
        1 + (P.q - 2) * tower.genus r ≤ tower.rationalPointCount r),
    ConcreteMaximalMinorLevelData P (level r hr hpoints)
  explicitAssembly : Prop
  explicitAssembly_proof : explicitAssembly

namespace ConcreteSectionFourInput

/-- Forget only the concrete packaging and feed the internally generated
certificates to the pre-existing Section 4 assembly theorem. -/
noncomputable def toSectionFourInput
    {tower : GarciaStichtenothTowerInput P}
    (input : ConcreteSectionFourInput P tower) :
    SectionFourInput P tower where
  constructionThreshold := input.constructionThreshold
  level := input.level
  minors := fun r hr hpoints ↦
    (input.minors r hr hpoints).toMaximalMinorLevelData
  explicitAssembly := input.explicitAssembly
  explicitAssembly_proof := input.explicitAssembly_proof

/-- Lemma 3.2 from the concrete trust boundary. -/
theorem lemma_3_2_concrete
    {tower : GarciaStichtenothTowerInput P}
    (input : ConcreteSectionFourInput P tower) :
    Nonempty (Lemma32DirectionFamily P) :=
  lemma_3_2 P tower input.toSectionFourInput

end ConcreteSectionFourInput

end Levels

end HDXLean
