import HDXLean.Basic

/-!
# Zero-sum triples in characteristic two

This file formalizes the triples

`{p, r, p + r}`

used in Section 3.2 of the paper.  The algebraic lemmas are stated for a
finite field of characteristic two.  The finite family at the end consists
of the unordered triples arising from ordered pairs of distinct nonzero
field elements.
-/

namespace HDXLean
namespace CharTwoTriples

open scoped BigOperators

set_option linter.unusedSectionVars false

variable {F : Type*} [Field F] [Fintype F] [DecidableEq F] [CharP F 2]

/-! ## Characteristic-two algebra -/

/-- Every element is its own additive inverse in characteristic two. -/
@[simp]
theorem add_self_eq_zero (x : F) : x + x = 0 := by
  have htwo : (2 : F) = 0 := CharP.cast_eq_zero F 2
  calc
    x + x = (2 : F) * x := (two_mul x).symm
    _ = 0 := by rw [htwo, zero_mul]

/-- In characteristic two, `p + r = 0` exactly when `p = r`. -/
theorem add_eq_zero_iff_eq (p r : F) : p + r = 0 ↔ p = r := by
  constructor
  · intro h
    calc
      p = p + 0 := by simp
      _ = p + (p + r) := by rw [h]
      _ = (p + p) + r := (add_assoc p p r).symm
      _ = r := by rw [add_self_eq_zero, zero_add]
  · rintro rfl
    exact add_self_eq_zero p

/-- The third entry `p + r` is nonzero when the first two entries differ. -/
theorem add_ne_zero_of_ne {p r : F} (hpr : p ≠ r) : p + r ≠ 0 := by
  exact fun h ↦ hpr ((add_eq_zero_iff_eq p r).mp h)

@[simp]
theorem add_add_cancel_left (p r : F) : p + (p + r) = r := by
  rw [← add_assoc, add_self_eq_zero, zero_add]

@[simp]
theorem add_add_cancel_right (p r : F) : r + (p + r) = p := by
  simpa [add_comm] using add_add_cancel_left r p

/-- Frobenius is additive for squares in characteristic two. -/
theorem add_sq (p r : F) : (p + r) ^ 2 = p ^ 2 + r ^ 2 := by
  have htwo : (2 : F) = 0 := CharP.cast_eq_zero F 2
  calc
    (p + r) ^ 2 = p ^ 2 + (2 : F) * p * r + r ^ 2 := by ring
    _ = p ^ 2 + r ^ 2 := by rw [htwo]; simp

/-! ## One unordered triple -/

/-- The unordered characteristic-two triple generated by `p` and `r`. -/
def triple (p r : F) : Finset F := {p, r, p + r}

@[simp]
theorem mem_triple {p r x : F} :
    x ∈ triple p r ↔ x = p ∨ x = r ∨ x = p + r := by
  simp [triple]

theorem triple_comm (p r : F) : triple p r = triple r p := by
  ext x
  simp [triple, add_comm, or_left_comm]

/-- A nonzero second entry differs from the sum. -/
theorem left_ne_sum {p r : F} (hr : r ≠ 0) : p ≠ p + r := by
  intro h
  have h' : p + 0 = p + r := by simpa using h
  exact hr (add_left_cancel h').symm

/-- A nonzero first entry differs from the sum. -/
theorem right_ne_sum {p r : F} (hp : p ≠ 0) : r ≠ p + r := by
  intro h
  have h' : r + 0 = r + p := by simpa [add_comm] using h
  exact hp (add_left_cancel h').symm

/-- The three displayed entries are pairwise distinct. -/
theorem entries_pairwise_distinct {p r : F} (hp : p ≠ 0) (hr : r ≠ 0)
    (hpr : p ≠ r) : p ≠ r ∧ p ≠ p + r ∧ r ≠ p + r :=
  ⟨hpr, left_ne_sum hr, right_ne_sum hp⟩

/-- The triple generated by distinct nonzero entries has cardinality three. -/
theorem card_triple {p r : F} (hp : p ≠ 0) (hr : r ≠ 0) (hpr : p ≠ r) :
    (triple p r).card = 3 := by
  have hps := left_ne_sum (p := p) hr
  have hrs := right_ne_sum (r := r) hp
  simp [triple, hpr, hps, hrs]

/-- Every member of a triple generated by nonzero distinct entries is nonzero. -/
theorem mem_triple_ne_zero {p r x : F} (hp : p ≠ 0) (hr : r ≠ 0)
    (hpr : p ≠ r) (hx : x ∈ triple p r) : x ≠ 0 := by
  rcases mem_triple.mp hx with rfl | rfl | rfl
  · exact hp
  · exact hr
  · exact add_ne_zero_of_ne hpr

theorem zero_not_mem_triple {p r : F} (hp : p ≠ 0) (hr : r ≠ 0)
    (hpr : p ≠ r) : 0 ∉ triple p r := by
  intro hzero
  exact mem_triple_ne_zero hp hr hpr hzero rfl

/-- The entries of a characteristic-two triple sum to zero. -/
theorem sum_triple {p r : F} (hp : p ≠ 0) (hr : r ≠ 0) (hpr : p ≠ r) :
    ∑ x ∈ triple p r, x = 0 := by
  have hps := left_ne_sum (p := p) hr
  have hrs := right_ne_sum (r := r) hp
  have hpnot : p ∉ ({r, p + r} : Finset F) := by simp [hpr, hps]
  have hrnot : r ∉ ({p + r} : Finset F) := by simp [hrs]
  rw [triple, Finset.sum_insert hpnot, Finset.sum_insert hrnot,
    Finset.sum_singleton, ← add_assoc, add_self_eq_zero]

/-- The squares of the entries also sum to zero. -/
theorem sum_sq_triple {p r : F} (hp : p ≠ 0) (hr : r ≠ 0) (hpr : p ≠ r) :
    ∑ x ∈ triple p r, x ^ 2 = 0 := by
  have hps := left_ne_sum (p := p) hr
  have hrs := right_ne_sum (r := r) hp
  have hpnot : p ∉ ({r, p + r} : Finset F) := by simp [hpr, hps]
  have hrnot : r ∉ ({p + r} : Finset F) := by simp [hrs]
  rw [triple, Finset.sum_insert hpnot, Finset.sum_insert hrnot,
    Finset.sum_singleton, add_sq]
  calc
    p ^ 2 + (r ^ 2 + (p ^ 2 + r ^ 2)) =
        (p ^ 2 + r ^ 2) + (p ^ 2 + r ^ 2) := by ac_rfl
    _ = 0 := add_self_eq_zero _

/-! ## Reconstruction from a pair -/

/-- Any two distinct entries of a triple regenerate the same unordered
triple. This is the pair-determines-one-triple property used in the paper. -/
theorem pair_determines_triple {p r a b : F}
    (ha : a ∈ triple p r) (hb : b ∈ triple p r) (hab : a ≠ b) :
    triple a b = triple p r := by
  rcases mem_triple.mp ha with rfl | rfl | rfl <;>
    rcases mem_triple.mp hb with rfl | rfl | rfl
  all_goals try { exact (hab rfl).elim }
  all_goals
    ext x
    simp [triple, add_comm, or_comm, or_left_comm, or_assoc]

/-! ## The finite family of all triples -/

/-- Ordered pairs of distinct nonzero field elements. -/
def admissiblePairs (F : Type*) [Field F] [Fintype F] [DecidableEq F] :
    Finset (F × F) :=
  Finset.univ.filter fun pr ↦ pr.1 ≠ 0 ∧ pr.2 ≠ 0 ∧ pr.1 ≠ pr.2

/-- The finite family of all unordered triples `{p,r,p+r}` with `p` and `r`
distinct and nonzero. Repeated presentations are removed by `Finset.image`. -/
def family (F : Type*) [Field F] [Fintype F] [DecidableEq F] :
    Finset (Finset F) :=
  (admissiblePairs F).image fun pr ↦ triple pr.1 pr.2

theorem mem_family_iff {t : Finset F} :
    t ∈ family F ↔
      ∃ p r : F, p ≠ 0 ∧ r ≠ 0 ∧ p ≠ r ∧ triple p r = t := by
  constructor
  · intro ht
    obtain ⟨pr, hpr, rfl⟩ := Finset.mem_image.mp ht
    have hadm : pr.1 ≠ 0 ∧ pr.2 ≠ 0 ∧ pr.1 ≠ pr.2 := by
      simpa [admissiblePairs] using hpr
    exact ⟨pr.1, pr.2, hadm.1, hadm.2.1, hadm.2.2, rfl⟩
  · rintro ⟨p, r, hp, hr, hpr, rfl⟩
    exact Finset.mem_image.mpr
      ⟨(p, r), by simp [admissiblePairs, hp, hr, hpr], rfl⟩

theorem triple_mem_family {p r : F} (hp : p ≠ 0) (hr : r ≠ 0) (hpr : p ≠ r) :
    triple p r ∈ family F :=
  mem_family_iff.mpr ⟨p, r, hp, hr, hpr, rfl⟩

theorem family_member_card {t : Finset F} (ht : t ∈ family F) : t.card = 3 := by
  obtain ⟨p, r, hp, hr, hpr, rfl⟩ := mem_family_iff.mp ht
  exact card_triple hp hr hpr

theorem family_member_zero_not_mem {t : Finset F} (ht : t ∈ family F) : 0 ∉ t := by
  obtain ⟨p, r, hp, hr, hpr, rfl⟩ := mem_family_iff.mp ht
  exact zero_not_mem_triple hp hr hpr

theorem family_member_sum {t : Finset F} (ht : t ∈ family F) :
    ∑ x ∈ t, x = 0 := by
  obtain ⟨p, r, hp, hr, hpr, rfl⟩ := mem_family_iff.mp ht
  exact sum_triple hp hr hpr

theorem family_member_sum_sq {t : Finset F} (ht : t ∈ family F) :
    ∑ x ∈ t, x ^ 2 = 0 := by
  obtain ⟨p, r, hp, hr, hpr, rfl⟩ := mem_family_iff.mp ht
  exact sum_sq_triple hp hr hpr

/-- A family member containing two distinct entries is exactly the triple
generated by those entries. -/
theorem family_eq_triple_of_pair {t : Finset F} (ht : t ∈ family F)
    {a b : F} (ha : a ∈ t) (hb : b ∈ t) (hab : a ≠ b) :
    t = triple a b := by
  obtain ⟨p, r, hp, hr, hpr, rfl⟩ := mem_family_iff.mp ht
  exact (pair_determines_triple ha hb hab).symm

/-- Every pair of distinct nonzero field elements lies in exactly one member
of the triple family. -/
theorem existsUnique_family_containing_pair {a b : F}
    (ha : a ≠ 0) (hb : b ≠ 0) (hab : a ≠ b) :
    ∃! t : Finset F, t ∈ family F ∧ a ∈ t ∧ b ∈ t := by
  refine ⟨triple a b, ?_, ?_⟩
  · exact ⟨triple_mem_family ha hb hab, by simp, by simp⟩
  · intro t ht
    exact family_eq_triple_of_pair ht.1 ht.2.1 ht.2.2 hab

/-! ## Exact size of the family -/

/-- Incidences between a family member and an ordered pair of distinct
elements of that member. -/
def incidences (F : Type*) [Field F] [Fintype F] [DecidableEq F] :
    Finset ((_t : Finset F) × (F × F)) :=
  (family F).sigma fun t ↦ t.offDiag

/-- Each family member contributes its six ordered pairs of distinct entries. -/
theorem card_incidences :
    (incidences F).card = (family F).card * 6 := by
  rw [incidences, Finset.card_sigma]
  apply Finset.sum_const_nat
  intro t ht
  rw [Finset.offDiag_card, family_member_card ht]

/-- Sending an admissible pair `(p,r)` to its unique containing triple and
remembering `(p,r)` is a bijection onto the incidence set. -/
theorem card_admissiblePairs_eq_card_incidences :
    (admissiblePairs F).card = (incidences F).card := by
  apply Finset.card_bij'
      (fun pr _ ↦ ⟨triple pr.1 pr.2, pr⟩)
      (fun z _ ↦ z.2)
  · intro pr _hpr
    rfl
  · intro z hz
    obtain ⟨t, pr⟩ := z
    have ht : t ∈ family F := (Finset.mem_sigma.mp hz).1
    have hpair : pr ∈ t.offDiag := (Finset.mem_sigma.mp hz).2
    have hp := Finset.mem_offDiag.mp hpair
    have heq : t = triple pr.1 pr.2 :=
      family_eq_triple_of_pair ht hp.1 hp.2.1 hp.2.2
    subst t
    rfl
  · intro pr hpr
    have hadm : pr.1 ≠ 0 ∧ pr.2 ≠ 0 ∧ pr.1 ≠ pr.2 := by
      simpa [admissiblePairs] using hpr
    rw [incidences, Finset.mem_sigma]
    exact ⟨triple_mem_family hadm.1 hadm.2.1 hadm.2.2,
      Finset.mem_offDiag.mpr ⟨by simp, by simp, hadm.2.2⟩⟩
  · intro z hz
    have hmem := (Finset.mem_sigma.mp hz).2
    have hpair := Finset.mem_offDiag.mp hmem
    have ht := (Finset.mem_sigma.mp hz).1
    have ha : z.2.1 ≠ 0 := fun hzero ↦
      family_member_zero_not_mem ht (hzero ▸ hpair.1)
    have hb : z.2.2 ≠ 0 := fun hzero ↦
      family_member_zero_not_mem ht (hzero ▸ hpair.2.1)
    simpa [admissiblePairs] using And.intro ha (And.intro hb hpair.2.2)

/-- Admissible pairs are exactly the off-diagonal of the nonzero elements. -/
theorem admissiblePairs_eq_offDiag_nonzero :
    admissiblePairs F = (Finset.univ.erase (0 : F)).offDiag := by
  ext pr
  simp [admissiblePairs]

/-- The number of ordered pairs of distinct nonzero field elements. -/
theorem card_admissiblePairs :
    (admissiblePairs F).card =
      (Fintype.card F - 1) * (Fintype.card F - 2) := by
  rw [admissiblePairs_eq_offDiag_nonzero, Finset.offDiag_card]
  simp only [Finset.card_erase_of_mem, Finset.mem_univ, Finset.card_univ]
  conv_lhs =>
    rhs
    rw [← Nat.mul_one (Fintype.card F - 1)]
  rw [← Nat.mul_sub_left_distrib]
  congr 1

/-- Division-free exact cardinality formula for the triple family. -/
theorem family_card_mul_six :
    (family F).card * 6 =
      (Fintype.card F - 1) * (Fintype.card F - 2) := by
  rw [← card_admissiblePairs, card_admissiblePairs_eq_card_incidences,
    card_incidences]

/-- The characteristic-two triple family has `(q - 1)(q - 2) / 6`
members, where `q` is the cardinality of the field. -/
theorem family_card :
    (family F).card =
      ((Fintype.card F - 1) * (Fintype.card F - 2)) / 6 := by
  rw [← family_card_mul_six]
  omega

end CharTwoTriples
end HDXLean
