import Mathlib.LinearAlgebra.LinearIndependent.Basic
import Mathlib.RingTheory.Ideal.Basic
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.FieldTheory.IsAlgClosed.Basic

/-!
# Actual 1-genericity and the minimal-generator bridge

The row and column operations in the definition of 1-genericity are encoded
by nonzero coefficient vectors.  Unlike the historical `oneGeneric : Prop`
field, this predicate refers to the entries of the actual matrix.

The elementary implications proved here are project-owned steps in
Proposition 4.6.  The determinantal input at the end isolates the cited
minimal-generator conclusion; it does not assume coefficient independence.
-/

namespace HDXLean

open scoped BigOperators

namespace OneGenericMatrix

universe u v

section Genericity

variable {F R C U V W : Type*} [Field F]
variable [Fintype R] [Fintype C]
variable [AddCommGroup U] [Module F U]
variable [AddCommGroup V] [Module F V]
variable [AddCommGroup W] [Module F W]

/-- No nonzero generalized row and generalized column have zero entry.
For a matrix of linear forms, `W` is its vector space of coefficients. -/
def IsOneGeneric (M : R → C → W) : Prop :=
  ∀ (a : R → F) (b : C → F), a ≠ 0 → b ≠ 0 →
    (∑ r, ∑ c, (a r * b c) • M r c) ≠ 0

/-- Linear independence makes every nontrivial linear combination nonzero. -/
theorem sum_smul_ne_zero {u : R → U} (hu : LinearIndependent F u)
    {a : R → F} (ha : a ≠ 0) : (∑ r, a r • u r) ≠ 0 := by
  intro hz
  apply ha
  funext r
  exact Fintype.linearIndependent_iff.mp hu a hz r

/-- The generalized matrix entry is the product of the generalized row and
column. This is the bilinear distributivity step in the manuscript. -/
theorem generalizedEntry_eq_product
    (multiply : U →ₗ[F] V →ₗ[F] W) (u : R → U) (v : C → V)
    (a : R → F) (b : C → F) :
    (∑ r, ∑ c, (a r * b c) • multiply (u r) (v c)) =
      multiply (∑ r, a r • u r) (∑ c, b c • v c) := by
  simp only [map_sum, map_smul, LinearMap.sum_apply, LinearMap.smul_apply,
    Finset.smul_sum, smul_smul]
  rw [Finset.sum_comm]
  simp only [mul_comm]

/-- Independent row and column functions in an integral multiplication
space produce an actually 1-generic multiplication matrix. The same theorem
is applied over the algebraic closure, not merely over the finite field. -/
theorem isOneGeneric_of_no_zero_products
    (multiply : U →ₗ[F] V →ₗ[F] W)
    (hproduct : ∀ u v, u ≠ 0 → v ≠ 0 → multiply u v ≠ 0)
    {u : R → U} {v : C → V}
    (hu : LinearIndependent F u) (hv : LinearIndependent F v) :
    IsOneGeneric (F := F) (fun r c ↦ multiply (u r) (v c)) := by
  intro a b ha hb
  rw [generalizedEntry_eq_product]
  exact hproduct _ _ (sum_smul_ne_zero hu ha) (sum_smul_ne_zero hv hb)

/-- An injective linear coefficient change preserves actual 1-genericity. -/
theorem IsOneGeneric.map {W' : Type*} [AddCommGroup W'] [Module F W']
    {M : R → C → W} (hM : IsOneGeneric (F := F) M)
    (f : W →ₗ[F] W') (hf : Function.Injective f) :
    IsOneGeneric (F := F) (fun r c ↦ f (M r c)) := by
  intro a b ha hb hz
  apply hM a b ha hb
  apply hf
  simpa only [map_sum, map_smul, map_zero] using hz

/-- Coordinate form of the multiplication argument. An injective
evaluation-coordinate map sends the products to the entrywise products of
the row and column evaluation coordinates. -/
theorem isOneGeneric_coordinates_of_no_zero_products {t : ℕ}
    (multiply : U →ₗ[F] V →ₗ[F] W)
    (hproduct : ∀ u v, u ≠ 0 → v ≠ 0 → multiply u v ≠ 0)
    {u : R → U} {v : C → V}
    (hu : LinearIndependent F u) (hv : LinearIndependent F v)
    (coordinate : W →ₗ[F] (Fin t → F))
    (hcoordinate : Function.Injective coordinate)
    (rowValue : R → Fin t → F) (columnValue : C → Fin t → F)
    (hentry : ∀ r c i,
      coordinate (multiply (u r) (v c)) i = rowValue r i * columnValue c i) :
    IsOneGeneric (F := F) (fun r c i ↦ rowValue r i * columnValue c i) := by
  have h := (isOneGeneric_of_no_zero_products multiply hproduct hu hv).map
    coordinate hcoordinate
  have heq : (fun r c ↦ coordinate (multiply (u r) (v c))) =
      (fun r c i ↦ rowValue r i * columnValue c i) := by
    funext r c i
    exact hentry r c i
  rw [heq] at h
  exact h

end Genericity

section MinimalGenerators

variable {F A J : Type*} [Field F] [CommRing A] [Algebra F A]

/-- A family generates its ideal minimally if no member belongs to the
ideal generated by the other members. This is ideal irredundancy, not an
assumed linear-independence conclusion. -/
def IdealIrredundant (p : J → A) : Prop :=
  ∀ j, p j ∉ Ideal.span (p '' {i | i ≠ j})

/-- Minimal ideal generators are linearly independent over the ground
field. This elementary bridge is proved here rather than absorbed into a
citation input. -/
theorem IdealIrredundant.linearIndependent {p : J → A}
    (hp : IdealIrredundant p) : LinearIndependent F p := by
  classical
  rw [linearIndependent_iff']
  intro s a hz j hj
  by_contra haj
  apply hp j
  let I : Ideal A := Ideal.span (p '' {i | i ≠ j})
  have hrest : (∑ i ∈ s.erase j, a i • p i) ∈ I := by
    apply I.sum_mem
    intro i hi
    exact (I.restrictScalars F).smul_mem (a i) (Ideal.subset_span
      ⟨i, Finset.ne_of_mem_erase hi, rfl⟩)
  have hterm : a j • p j ∈ I := by
    have heq : a j • p j = -(∑ i ∈ s.erase j, a i • p i) := by
      rw [← Finset.sum_erase_add _ _ hj] at hz
      exact eq_neg_of_add_eq_zero_right hz
    rw [heq]
    exact I.neg_mem hrest
  have hunit := (I.restrictScalars F).smul_mem (a j)⁻¹ hterm
  change (a j)⁻¹ • (a j • p j) ∈ I at hunit
  have hpj : p j ∈ I := by
    simpa only [smul_smul, inv_mul_cancel₀ haj, one_smul] using hunit
  exact hpj

end MinimalGenerators

section IrredundancyTransport

variable {A B J J' : Type*} [CommRing A] [CommRing B]

/-- Local minimality implies global minimality: membership in a globally
generated ideal would remain membership after applying the localization
map. This holds for every ring homomorphism. -/
theorem IdealIrredundant.of_map (f : A →+* B) {p : J → A}
    (hp : IdealIrredundant (fun j ↦ f (p j))) : IdealIrredundant p := by
  intro j hj
  apply hp j
  have hmap := Ideal.mem_map_of_mem f hj
  simpa only [Ideal.map_span, Set.image_image] using hmap

/-- Any subfamily of a minimal family of ideal generators is again
irredundant. This justifies selecting only some maximal minors. -/
theorem IdealIrredundant.comp {p : J → A} (hp : IdealIrredundant p)
    (e : J' → J) (he : Function.Injective e) :
    IdealIrredundant (p ∘ e) := by
  intro j hj
  apply hp (e j)
  apply Ideal.span_mono (s := (p ∘ e) '' {i | i ≠ j})
    (t := p '' {i | i ≠ e j}) ?_ hj
  rintro x ⟨i, hi, rfl⟩
  exact ⟨e i, fun h ↦ hi (he h), rfl⟩

end IrredundancyTransport

section DeterminantalCitation

variable (K : Type u) [Field K]

/-- Polynomial linear form with the specified coordinate coefficients. -/
noncomputable def linearForm {t : ℕ} (w : Fin t → K) :
    MvPolynomial (Fin t) K :=
  ∑ i, MvPolynomial.C (w i) * MvPolynomial.X i

/-- A literal maximal minor of a rectangular matrix of linear forms. -/
noncomputable def polynomialMinor {k m t : ℕ}
    (M : Fin k → Fin m → Fin t → K)
    (column : Fin k → Fin m) : MvPolynomial (Fin t) K :=
  Matrix.det (fun i j ↦ linearForm K (M i (column j)))

/-- Coefficient-matrix version of the cited determinantal
minimal-generator consequence of Eisenbud, Theorem 6.4 and Corollary A2.61.

The coefficient field is algebraically closed. Rows are nonempty; there
are at least as many columns as rows. Actual 1-genericity is required over
that field, and two selected minors cannot use the same column subset.
The output concerns ideal generators of literal polynomial determinants.
It does not mention the paper's evaluation maps or Boolean-cube coefficients.

The two cited results give the expected grade and minimality after
localization at the homogeneous maximal ideal. Local minimality implies
the global irredundancy recorded here. The ground-field linear-independence
consequence is proved separately above.
-/
structure EisenbudMinimalGeneratorsInput [IsAlgClosed K] : Prop where
  maximalMinors_irredundant : ∀ {k m t : ℕ} {J : Type v}
    (_hk : 0 < k) (_hkm : k ≤ m)
    (M : Fin k → Fin m → Fin t → K),
    IsOneGeneric (F := K) M →
    ∀ (column : J → Fin k → Fin m),
      (∀ j, Function.Injective (column j)) →
      Function.Injective (fun j ↦ Set.range (column j)) →
      IdealIrredundant (fun j ↦ polynomialMinor K M (column j))

/-- The actual cited minimal-generator statement yields polynomial
independence through the internally proved ideal-to-vector-space bridge. -/
theorem polynomialMinors_linearIndependent
    [IsAlgClosed K]
    (input : EisenbudMinimalGeneratorsInput.{u,v} K)
    {k m t : ℕ} {J : Type v} (hk : 0 < k) (hkm : k ≤ m)
    (M : Fin k → Fin m → Fin t → K)
    (hM : IsOneGeneric (F := K) M)
    (column : J → Fin k → Fin m)
    (hcolumn : ∀ j, Function.Injective (column j))
    (hdistinct : Function.Injective (fun j ↦ Set.range (column j))) :
    LinearIndependent K (fun j ↦ polynomialMinor K M (column j)) :=
  IdealIrredundant.linearIndependent (F := K)
    (input.maximalMinors_irredundant (J := J) hk hkm M hM column hcolumn hdistinct)

end DeterminantalCitation

end OneGenericMatrix

end HDXLean
